[package]
name = "swc_plugin_import_meta_env"
version = "0.1.0"
edition = "2021"
authors = ["Alex Miller <codex.nz@gmail.com>"]
description = "SWC plugin for handling the transformation of import.meta.env"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
# debug = true
lto = true

[dependencies]
swc_core = { version = "0.79.*", features = [
    "ecma_plugin_transform",
    "trace_macro",
] }
tracing = "0.1.37"

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
