name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Handle line endings
        shell: bash
        if: runner.os == 'Windows'
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - name: Configure path (windows)
        shell: bash
        if: runner.os == 'Windows'
        run: |
          echo 'C:\\npm\\prefix' >> $GITHUB_PATH
      - name: Run tests
        run: pnpm run test
  release:
    needs: test
    if: ${{ github.event_name == 'push' }}
    secrets: inherit
    uses: ./.github/workflows/release.yml
