name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Handle line endings
        shell: bash
        if: runner.os == 'Windows'
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: pnpm i --frozen-lockfile
      - name: Configure rustup
        run: |
          rustup set profile minimal
          rustup target add wasm32-wasi
      - name: Configure path (windows)
        shell: bash
        if: runner.os == 'Windows'
        run: |
          echo 'C:\\npm\\prefix' >> $GITHUB_PATH
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cargo-test"
          cache-on-failure: true
      - name: Run tests
        run: pnpm run test
